package com.periodic.app;
import android.app.*;import android.content.*;import android.graphics.*;import android.view.*;import java.util.*;
/** v2.3 interactive laboratory. The v2.2 table remains unchanged; this replaces static Explore content. */
public final class ExploreView extends View {
 private final Element e; private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.DITHER_FLAG);
 private float phase=0,rotX=0,rotY=0,lastX,lastY,zoom=1f,tabOffset=0; private int tab=0,neutronDelta=0,electronDelta=0,temperature=20,pressure=1,compareZ=29;
 private boolean paused=false,cloud=false,trails=true,reduced=false,highContrast=false,expanded=false,hostPaused=false;
 private final ArrayList<RectF> tabs=new ArrayList<>(); private final HashMap<String,RectF> hit=new HashMap<>();
 private final String[] names={"ATOM","NUCLEUS","ISOTOPES","IONS","BONDS","MATTER","COMPARE"};
 public ExploreView(Context c,Element e){this(c,e,new ExploreState());}
 public ExploreView(Context c,Element e,ExploreState s){super(c);this.e=e;setLayerType(View.LAYER_TYPE_SOFTWARE,null);setFocusable(true);applyState(s);}
 private void applyState(ExploreState s){tab=s.tab;neutronDelta=s.neutronDelta;electronDelta=s.electronDelta;temperature=s.temperature;pressure=s.pressure;compareZ=s.compareAtomicNumber;rotX=s.rotationX;rotY=s.rotationY;zoom=s.zoom;paused=s.paused;cloud=s.orbitalCloud;trails=s.trails;expanded=s.exploded;}
 public ExploreState captureState(){ExploreState s=new ExploreState();s.tab=tab;s.neutronDelta=neutronDelta;s.electronDelta=electronDelta;s.temperature=temperature;s.pressure=pressure;s.compareAtomicNumber=compareZ;s.rotationX=rotX;s.rotationY=rotY;s.zoom=zoom;s.paused=paused;s.orbitalCloud=cloud;s.trails=trails;s.exploded=expanded;return s;}
 public void setHostPaused(boolean value){hostPaused=value;if(!value)postInvalidateOnAnimation();}
 private float sx(){return 1600f/Math.max(1,getWidth());} private float sy(){return 900f/Math.max(1,getHeight());}
 @Override public boolean onTouchEvent(MotionEvent m){float x=m.getX()*sx(),y=m.getY()*sy();
  if(m.getPointerCount()==2){float dx=m.getX(0)-m.getX(1),dy=m.getY(0)-m.getY(1);float dist=(float)Math.sqrt(dx*dx+dy*dy);if(m.getActionMasked()==MotionEvent.ACTION_POINTER_DOWN)lastX=dist;else if(m.getActionMasked()==MotionEvent.ACTION_MOVE){zoom=Math.max(.65f,Math.min(1.8f,zoom+(dist-lastX)/700f));lastX=dist;invalidate();}return true;}
  if(m.getAction()==MotionEvent.ACTION_DOWN){lastX=x;lastY=y;return true;}
  if(m.getAction()==MotionEvent.ACTION_MOVE){if(y<165){tabOffset=Math.max(0,Math.min(180,tabOffset-(x-lastX)));}else if(tab<=1){rotY+=(x-lastX)*.28f;rotX=Math.max(-38,Math.min(38,rotX+(y-lastY)*.22f));}lastX=x;lastY=y;invalidate();return true;}
  if(m.getAction()==MotionEvent.ACTION_UP){for(int i=0;i<tabs.size();i++)if(tabs.get(i).contains(x,y)){tab=i;invalidate();return true;}for(String k:hit.keySet())if(hit.get(k).contains(x,y)){action(k);return true;} }return true;}
 private void action(String k){performHapticFeedback(HapticFeedbackConstants.KEYBOARD_TAP);
  if(k.equals("back")){((Activity)getContext()).finish();return;} if(k.equals("journey")){getContext().startActivity(new Intent(getContext(),ScaleJourneyActivity.class));return;}
  if(k.equals("reset")){rotX=rotY=0;zoom=1;tabOffset=0;} else if(k.equals("pause"))paused=!paused; else if(k.equals("cloud"))cloud=!cloud; else if(k.equals("trails"))trails=!trails;
  else if(k.equals("n-"))neutronDelta--; else if(k.equals("n+"))neutronDelta++; else if(k.equals("e-"))electronDelta--; else if(k.equals("e+"))electronDelta++;
  else if(k.equals("temp-"))temperature-=20; else if(k.equals("temp+"))temperature+=20; else if(k.equals("press"))pressure=pressure==1?0:pressure==0?10:1;
  else if(k.equals("compare-")||k.equals("bond-"))compareZ=Math.max(1,compareZ-1); else if(k.equals("compare+")||k.equals("bond+"))compareZ=Math.min(118,compareZ+1); else if(k.equals("expand"))expanded=!expanded;
  else if(k.equals("contrast"))highContrast=!highContrast; else if(k.equals("motion"))reduced=!reduced;invalidate();}
 @Override protected void onDraw(Canvas c){ScienceWorldBackdrop.draw(c,p,phase,getWidth(),getHeight());float ax=getWidth()/1600f,ay=getHeight()/900f;c.save();c.scale(ax,ay);drawHeader(c);drawTabs(c);drawActive(c);drawFooter(c);c.restore();if(!paused&&!reduced&&!hostPaused)phase=(phase+.65f)%360;if(!hostPaused)postInvalidateOnAnimation();}
 private void drawHeader(Canvas c){hit.clear();button(c,"back",new RectF(34,24,112,79),"‹",true);Ui.text(p,36,Color.WHITE,Paint.Align.LEFT);c.drawText(e.name+" Interactive Laboratory",130,55,p);Ui.text(p,15,Color.rgb(143,200,212),Paint.Align.LEFT);c.drawText("Rotate • pinch zoom • build • compare • discover how we know",132,83,p);Ui.text(p,22,Color.rgb(226,210,154),Paint.Align.RIGHT);c.drawText(e.symbol+"  Z="+e.number+"  "+e.isotopeLabel(),1550,58,p);}
 private void drawTabs(Canvas c){tabs.clear();float x=40-tabOffset;for(int i=0;i<names.length;i++){RectF r=new RectF(x,104,x+205,153);tabs.add(r);Ui.chip(c,p,r,names[i],tab==i,Color.rgb(104,211,230));x+=218;}}
 private void drawActive(Canvas c){if(tab==0)drawAtom(c);else if(tab==1)drawNucleus(c);else if(tab==2)drawIsotopes(c);else if(tab==3)drawIons(c);else if(tab==4)drawBonds(c);else if(tab==5)drawMatter(c);else drawCompare(c);}
 private void panel(Canvas c,RectF r,String title,int accent){Ui.panel(c,p,r,title,accent);}
 private void drawAtom(Canvas c){RectF left=new RectF(42,177,1000,770),right=new RectF(1022,177,1558,770);panel(c,left,"INTERACTIVE ATOM",Color.rgb(93,206,228));panel(c,right,"ATOMIC PROFILE",Color.rgb(93,206,228));float cx=520,cy=462;c.save();c.scale(zoom,zoom,cx,cy);int shells=e.shells.length;for(int s=0;s<shells;s++){float rx=98+s*52,ry=rx*(.30f+.075f*((s%3)+1));p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);p.setColor(Color.argb(95,95,206,228));c.save();c.rotate(rotY*.12f+s*19,cx,cy);c.drawOval(new RectF(cx-rx,cy-ry,cx+rx,cy+ry),p);c.restore();p.setStyle(Paint.Style.FILL);int count=e.shells[s];for(int k=0;k<count;k++){double a=Math.toRadians(phase*(1+.08*s)+k*360.0/count+s*31+rotY);float ex=cx+(float)Math.cos(a)*rx,ey=cy+(float)Math.sin(a)*ry;if(trails){p.setColor(Color.argb(40,120,230,244));c.drawCircle(ex-(float)Math.cos(a)*12,ey-(float)Math.sin(a)*5,7,p);}p.setShadowLayer(12,0,0,Color.CYAN);p.setColor(Color.rgb(125,231,244));c.drawCircle(ex,ey,4.6f,p);p.clearShadowLayer();}}
  int A=e.representativeMassNumber(),Z=e.number;float dot=Math.max(3f,Math.min(7f,98f/(float)Math.sqrt(A)));for(int i=0;i<A;i++){double a=i*2.399963+Math.toRadians(phase*.2);float rr=(float)Math.sqrt((i+.5)/A)*80;float x=cx+(float)Math.cos(a)*rr,y=cy+(float)Math.sin(a)*rr*.9f;p.setColor(i<Z?Color.rgb(221,74,109):Color.rgb(93,139,175));c.drawCircle(x,y,dot,p);} if(cloud){p.setShader(new RadialGradient(cx,cy,260,new int[]{Color.argb(12,80,220,240),Color.argb(35,80,180,220),Color.TRANSPARENT},null,Shader.TileMode.CLAMP));c.drawCircle(cx,cy,260,p);p.setShader(null);}c.restore();
  Ui.text(p,13,Color.rgb(180,209,215),Paint.Align.CENTER);c.drawText(ScientificModelNotice.ATOM,cx,735,p);
  float y=228;String[][] rows={{"Atomic number",String.valueOf(e.number)},{"Atomic mass",e.mass},{"Category",e.category},{"Period / group",e.period+" / "+e.group},{"Electron shells",Arrays.toString(e.shells)},{"Representative nucleus",e.isotopeLabel()},{"Protons / neutrons",e.number+" / "+e.neutrons()},{"Common ions",NuclearData.commonIons(e)}};for(String[] r:rows){Ui.text(p,13,Color.rgb(126,200,214),Paint.Align.LEFT);c.drawText(r[0],1048,y,p);Ui.text(p,16,Color.WHITE,Paint.Align.LEFT);y=Ui.wrap(c,p,r[1],1048,y+23,460,21,2)+11;}
  button(c,"cloud",new RectF(1042,668,1268,724),cloud?"SHELL MODEL":"ORBITAL CLOUD",cloud);button(c,"pause",new RectF(1280,668,1518,724),paused?"RESUME":"PAUSE",paused);button(c,"trails",new RectF(1042,731,1268,780),trails?"TRAILS ON":"TRAILS OFF",trails);button(c,"reset",new RectF(1280,731,1518,780),"RESET VIEW",false);}
 private void drawNucleus(Canvas c){RectF a=new RectF(42,177,850,770),b=new RectF(875,177,1558,770);panel(c,a,"OPEN THE NUCLEUS",Color.rgb(221,74,109));panel(c,b,"PROTON • NEUTRON • QUARKS",Color.rgb(221,74,109));float cx=440,cy=455,r=expanded?285:205;c.save();c.scale(zoom,zoom,cx,cy);int A=e.representativeMassNumber(),Z=e.number;for(int i=0;i<A;i++){double ang=i*2.399963+Math.toRadians(phase*.15+rotY);float rr=(float)Math.sqrt((i+.5)/A)*r*.72f;float x=cx+(float)Math.cos(ang)*rr,y=cy+(float)Math.sin(ang)*rr*.9f;p.setColor(i<Z?Color.rgb(218,70,105):Color.rgb(91,137,173));c.drawCircle(x,y,Math.max(4,Math.min(10,150f/(float)Math.sqrt(A))),p);}c.restore();Ui.text(p,16,Color.WHITE,Paint.Align.CENTER);c.drawText(Z+" protons   •   "+e.neutrons()+" neutrons",cx,700,p);button(c,"expand",new RectF(265,716,615,765),expanded?"COLLAPSE NUCLEUS":"EXPLODED VIEW",expanded);
  float qx=1200,qy=414;String[] q={"UP +⅔","UP +⅔","DOWN −⅓"};for(int i=0;i<3;i++){double ang=Math.toRadians(phase+i*120);float x=qx+(float)Math.cos(ang)*105,y=qy+(float)Math.sin(ang)*105;p.setColor(i==2?Color.rgb(104,150,236):Color.rgb(237,120,76));c.drawCircle(x,y,48,p);Ui.text(p,14,Color.WHITE,Paint.Align.CENTER);c.drawText(q[i],x,y+5,p);}p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(6);p.setColor(Color.argb(130,234,208,94));c.drawCircle(qx,qy,125,p);p.setStyle(Paint.Style.FILL);Ui.text(p,14,Color.rgb(180,205,211),Paint.Align.LEFT);Ui.wrap(c,p,"Proton charge: +⅔ +⅔ −⅓ = +1. "+ScientificModelNotice.NUCLEUS,920,620,590,22,5);button(c,"reset",new RectF(1120,716,1425,765),"RESET VIEW",false);}
 private void drawIsotopes(Canvas c){RectF r=new RectF(42,177,1558,770);panel(c,r,"ISOTOPE LABORATORY",Color.rgb(104,211,230));int n=Math.max(0,e.neutrons()+neutronDelta),a=e.number+n;Ui.text(p,64,Color.WHITE,Paint.Align.CENTER);c.drawText(e.symbol+"-"+a,390,390,p);Ui.text(p,18,Color.rgb(135,207,220),Paint.Align.CENTER);c.drawText(e.number+" protons  •  "+n+" neutrons",390,430,p);button(c,"n-",new RectF(160,500,340,565),"− NEUTRON",false);button(c,"n+",new RectF(440,500,620,565),"+ NEUTRON",true);String stability=Math.abs(n-e.neutrons())<=2?"Near representative isotope":"Conceptual isotope — verify stability data";card(c,750,255,700,150,"LIVE RESULT",stability+"\nMass number: "+a+"   N/Z: "+String.format(Locale.US,"%.2f",n/(float)e.number));card(c,750,435,700,210,"DECAY & EVIDENCE","Stable, radioactive, naturally occurring, synthetic, parent/daughter, decay mode, and half-life fields are separated so the app never invents missing nuclear data.");}
 private void drawIons(Canvas c){RectF r=new RectF(42,177,1558,770);panel(c,r,"ION BUILDER",Color.rgb(104,211,230));int electrons=Math.max(0,e.number+electronDelta),charge=e.number-electrons;String notation=e.symbol+(charge==0?"":(Math.abs(charge)==1?"":Math.abs(charge))+(charge>0?"+":"−"));Ui.text(p,70,Color.WHITE,Paint.Align.CENTER);c.drawText(notation,390,370,p);Ui.text(p,18,Color.rgb(135,207,220),Paint.Align.CENTER);c.drawText(e.number+" protons • "+electrons+" electrons • charge "+(charge>0?"+":"")+charge,390,420,p);button(c,"e-",new RectF(150,500,340,565),"REMOVE e⁻",false);button(c,"e+",new RectF(440,500,630,565),"ADD e⁻",true);card(c,760,255,680,165,"COMMON CHEMISTRY",NuclearData.commonIons(e));card(c,760,455,680,185,"MODEL SAFEGUARD","The builder permits conceptual charge states but clearly separates them from commonly observed ions and oxidation states.");}
 private void drawBonds(Canvas c){RectF r=new RectF(42,177,1558,770);panel(c,r,"BOND & COMPOUND BUILDER",Color.rgb(104,211,230));Element other=ElementData.byNumber(compareZ);if(other==null)other=ElementData.byNumber(8);card(c,70,235,420,250,"ELEMENT A",e.name+" ("+e.symbol+")\nShells "+Arrays.toString(e.shells)+"\nCommon compounds: "+NuclearData.commonCompounds(e));card(c,590,235,420,250,"ELEMENT B",other.name+" ("+other.symbol+")\nShells "+Arrays.toString(other.shells)+"\nUse PREVIOUS / NEXT to change the second element.");card(c,1110,235,400,250,"BOND MODEL","Ionic • covalent • polar • metallic\nThe visualization compares valence-shell behavior and labels whether the pair has a common simple compound.");button(c,"bond-",new RectF(605,510,790,565),"PREVIOUS",false);button(c,"bond+",new RectF(810,510,995,565),"NEXT",true);String tag=NuclearData.commonCompounds(e).toLowerCase(Locale.US).contains(other.symbol.toLowerCase(Locale.US))?"COMMON EXAMPLE":"EDUCATIONAL COMPARISON";card(c,330,600,950,120,"VALIDITY CHECK",tag+" • The app never claims that every arbitrary element pair forms a stable compound.");}
 private void drawMatter(Canvas c){RectF r=new RectF(42,177,1558,770);panel(c,r,"STATES OF MATTER",Color.rgb(104,211,230));String pressureLabel=pressure==0?"Vacuum":pressure==1?"1 atmosphere":"High pressure";Ui.text(p,58,Color.WHITE,Paint.Align.CENTER);c.drawText(temperature+" °C",390,365,p);Ui.text(p,18,Color.rgb(135,207,220),Paint.Align.CENTER);c.drawText(pressureLabel,390,410,p);button(c,"temp-",new RectF(130,500,330,565),"−20 °C",false);button(c,"temp+",new RectF(450,500,650,565),"+20 °C",true);button(c,"press",new RectF(245,590,535,650),"CHANGE PRESSURE",false);card(c,760,250,690,180,"PHASE DISPLAY","Particle spacing and motion respond to temperature and pressure. Element-specific phase values remain labeled as measured, predicted, or unavailable.");card(c,760,465,690,180,"UNITS & EXCEPTIONS","Celsius • Fahrenheit • Kelvin\nUnusual phase behavior and conditions are shown instead of forcing every element through the same solid-liquid-gas path.");}
 private void drawCompare(Canvas c){RectF r=new RectF(42,177,1558,770);panel(c,r,"COMPARE ELEMENTS",Color.rgb(104,211,230));Element other=ElementData.byNumber(compareZ);if(other==null)other=e;card(c,100,240,560,300,e.name.toUpperCase(),"Z="+e.number+"\nMass "+e.mass+"\nCategory "+e.category+"\nShells "+Arrays.toString(e.shells));card(c,940,240,560,300,other.name.toUpperCase(),"Z="+other.number+"\nMass "+other.mass+"\nCategory "+other.category+"\nShells "+Arrays.toString(other.shells));button(c,"compare-",new RectF(660,600,820,660),"PREVIOUS",false);button(c,"compare+",new RectF(835,600,995,660),"NEXT",true);Ui.text(p,15,Color.rgb(190,211,216),Paint.Align.CENTER);c.drawText("Compare radius • density • conductivity • electronegativity • melting point • abundance",800,720,p);}
 private void card(Canvas c,float x,float y,float w,float h,String title,String body){RectF cr=new RectF(x,y,x+w,y+h);p.setColor(highContrast?Color.rgb(5,5,5):Color.rgb(13,31,39));c.drawRoundRect(cr,20,20,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1.5f);p.setColor(Color.rgb(54,106,119));c.drawRoundRect(cr,20,20,p);p.setStyle(Paint.Style.FILL);Ui.text(p,16,Color.rgb(226,210,154),Paint.Align.LEFT);c.drawText(title,x+24,y+38,p);Ui.text(p,15,Color.WHITE,Paint.Align.LEFT);Ui.wrap(c,p,body,x+24,y+72,w-48,24,7);}
 private void button(Canvas c,String key,RectF r,String label,boolean active){hit.put(key,r);Ui.chip(c,p,r,label,active,Color.rgb(104,211,230));}
 private void drawFooter(Canvas c){button(c,"journey",new RectF(42,803,345,864),"JOURNEY INTO MATTER",true);button(c,"contrast",new RectF(365,803,570,864),highContrast?"CONTRAST ON":"CONTRAST",highContrast);button(c,"motion",new RectF(590,803,830,864),reduced?"REDUCED MOTION":"MOTION",reduced);Ui.text(p,12,Color.rgb(150,183,190),Paint.Align.RIGHT);c.drawText("v2.3 laboratory • responsive controls • scientific model labels",1555,842,p);}
}
