package com.periodic.app;
import android.app.*;import android.content.*;import android.graphics.*;import android.view.*;
public final class ScaleJourneyView extends View{
 private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.DITHER_FLAG);private float phase=0,drag=0,lastX,zoom=1;private int index=0;private boolean paused=false,labelsOn=true,hostPaused=false;private final RectF back=new RectF(),pause=new RectF(),labelButton=new RectF();
 private final String[] labels={"Human","Hand","Skin","Cell","Cell nucleus","DNA","Protein","Molecule","Atom","Electron cloud","Atomic nucleus","Proton","Quark scale"};
 private final String[] sizes={"~10⁰ m","~10⁻¹ m","~10⁻³ m","~10⁻⁵ m","~10⁻⁶ m","~10⁻⁹ m wide","~10⁻⁹–10⁻⁸ m","~10⁻⁹ m","~10⁻¹⁰ m","~10⁻¹⁰ m","~10⁻¹⁴–10⁻¹⁵ m","~10⁻¹⁵ m","tested below 10⁻¹⁸ m"};
 private final String[] notes={"Begin at ordinary human scale.","A familiar object anchors the zoom.","Layers of tissue contain countless cells.","Cells are complex molecular systems.","Genetic material is stored here in many cells.","DNA is only a few nanometers wide.","Proteins fold into working molecular machines.","Molecules are bonded groups of atoms.","Most atomic volume is electron probability distribution.","Not a hard shell: a quantum probability region.","Tiny compared with the whole atom.","Protons and neutrons are composite particles.","Quarks behave point-like at current experimental limits."};
 public ScaleJourneyView(Context c){this(c,8);}
 public ScaleJourneyView(Context c,int initialStage){super(c);index=Math.max(0,Math.min(labels.length-1,initialStage));setLayerType(View.LAYER_TYPE_SOFTWARE,null);}
 public int getStage(){return index;}
 public void setHostPaused(boolean value){hostPaused=value;if(!value)postInvalidateOnAnimation();}
 @Override public boolean onTouchEvent(MotionEvent e){float x=e.getX()*1600f/getWidth(),y=e.getY()*900f/getHeight();if(e.getPointerCount()==2){return true;}if(e.getAction()==MotionEvent.ACTION_DOWN){lastX=x;return true;}if(e.getAction()==MotionEvent.ACTION_MOVE){drag=x-lastX;invalidate();return true;}if(e.getAction()==MotionEvent.ACTION_UP){if(back.contains(x,y)){((Activity)getContext()).finish();return true;}if(pause.contains(x,y)){paused=!paused;invalidate();return true;}if(labelButton.contains(x,y)){labelsOn=!labelsOn;invalidate();return true;}if(drag<-60&&index<labels.length-1)index++;else if(drag>60&&index>0)index--;else if(y>700)index=Math.max(0,Math.min(labels.length-1,(int)((x-90)/1420f*labels.length)));drag=0;performHapticFeedback(HapticFeedbackConstants.KEYBOARD_TAP);invalidate();return true;}return true;}
 @Override protected void onDraw(Canvas c){ScienceWorldBackdrop.draw(c,p,phase,getWidth(),getHeight());float sx=getWidth()/1600f,sy=getHeight()/900f;c.save();c.scale(sx,sy);drawJourneyContent(c);c.restore();if(!paused&&!hostPaused)phase=(phase+.55f)%360;if(!hostPaused)postInvalidateOnAnimation();}
 private void drawJourneyContent(Canvas c){back.set(30,24,105,78);Ui.chip(c,p,back,"‹",true,Color.rgb(104,211,230));pause.set(1330,26,1530,76);Ui.chip(c,p,pause,paused?"RESUME":"PAUSE",paused,Color.rgb(104,211,230));labelButton.set(1100,26,1310,76);Ui.chip(c,p,labelButton,labelsOn?"LABELS ON":"LABELS OFF",labelsOn,Color.rgb(104,211,230));Ui.text(p,38,Color.WHITE,Paint.Align.CENTER);c.drawText("A JOURNEY INTO MATTER",800,62,p);Ui.text(p,15,Color.rgb(143,201,214),Paint.Align.CENTER);c.drawText("Swipe continuously inward or tap any stage on the logarithmic scale",800,91,p);
  float cx=800+drag*.35f,cy=385;float pulse=1+.035f*(float)Math.sin(Math.toRadians(phase*2));drawStage(c,cx,cy,pulse);Ui.text(p,21,Color.rgb(226,210,154),Paint.Align.CENTER);c.drawText(sizes[index],cx,cy+184,p);Ui.text(p,16,Color.rgb(190,211,216),Paint.Align.CENTER);Ui.wrap(c,p,notes[index],545,cy+225,510,25,3);Ui.text(p,13,Color.rgb(150,183,190),Paint.Align.CENTER);c.drawText("Evidence: microscopy • spectroscopy • scattering • crystallography • particle detectors",800,674,p);
  float y=755,start=90,end=1510;p.setStrokeWidth(5);p.setColor(Color.rgb(45,92,105));c.drawLine(start,y,end,y,p);for(int i=0;i<labels.length;i++){float x=start+(end-start)*i/(labels.length-1f);p.setColor(i==index?Color.rgb(122,226,240):Color.rgb(65,112,126));c.drawCircle(x,y,i==index?12:7,p);if(labelsOn&&(i==index||i%2==0)){Ui.text(p,11,i==index?Color.WHITE:Color.rgb(151,183,190),Paint.Align.CENTER);c.drawText(labels[i],x,y+34+(i%2)*16,p);}}
  Ui.text(p,13,Color.rgb(170,196,202),Paint.Align.LEFT);c.drawText("OUTWARD",72,840,p);Ui.text(p,13,Color.rgb(170,196,202),Paint.Align.RIGHT);c.drawText("INWARD",1528,840,p);Ui.text(p,12,Color.rgb(143,173,180),Paint.Align.CENTER);c.drawText(ScientificModelNotice.SCALE,800,878,p);}
 private void drawStage(Canvas c,float cx,float cy,float pulse){int accent=Color.rgb(80+index*9%140,135+index*7%85,180+index*5%70);p.setStyle(Paint.Style.STROKE);for(int ring=5;ring>=1;ring--){p.setStrokeWidth(2);p.setColor(Color.argb(24+ring*10,95,205,225));c.drawCircle(cx,cy,(90+ring*42)*pulse,p);}p.setStyle(Paint.Style.FILL);p.setShadowLayer(38,0,0,Color.argb(160,60,200,230));p.setColor(accent);c.drawCircle(cx,cy,132*pulse,p);p.clearShadowLayer();
  if(index==5){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(9);p.setColor(Color.WHITE);Path a=new Path(),b=new Path();for(int i=0;i<=90;i++){float yy=cy-100+i*2.2f;float xx=(float)Math.sin(i*.32+phase*.025)*38;a.lineTo(cx-22+xx,yy);b.lineTo(cx+22-xx,yy);}c.drawPath(a,p);c.drawPath(b,p);p.setStyle(Paint.Style.FILL);} else if(index>=8&&index<=10){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);p.setColor(Color.argb(180,180,240,250));for(int i=0;i<3;i++){c.save();c.rotate(i*60+phase*.2f,cx,cy);c.drawOval(new RectF(cx-110,cy-35,cx+110,cy+35),p);c.restore();}p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(220,75,108));c.drawCircle(cx,cy,index==10?30:15,p);} else if(index==11||index==12){for(int i=0;i<3;i++){double a=Math.toRadians(phase+i*120);p.setColor(i==2?Color.rgb(105,151,236):Color.rgb(238,120,76));c.drawCircle(cx+(float)Math.cos(a)*62,cy+(float)Math.sin(a)*62,28,p);}} 
  Ui.text(p,index==4?26:33,Color.WHITE,Paint.Align.CENTER);c.drawText(labels[index],cx,cy+10,p);}
}
